#---------------------------
#  PREPARE VOLUNTEER DATA
#---------------------------

#Lots of work to do here but skipping for now to get prototype working in Shiny

library(dplyr)
library(stringr)
library(tidyr)

df <- read.csv("./../../data/Fall 2021 Volunteer Form (Responses) - Form Responses 1.csv")

names(df) <- c(   'timestamp',
                  'email_address', 
                  'notes',
                  'placed_as_tutor_teacher', 
                  'proof_of_vax', 
                  'vol_intention', 
                  'leave_wec_full_name',
                  'leave_student_name_tutor',
                  'student_notified_indicator',
                  'first_name',
                  'last_name',
                  'phone_num',
                  'returning_indicator',
                  'previous_role',
                  'reserved_student_names',
                  'reregister_ackn_1',
                  'reregister_ackn_2',
                  'desired_start_date',
                  'details_multiple_dates',
                  'want_new_student_role_indicator',
                  'where_hear_wec',
                  'why_serve',
                  'past_apply_not_placed',
                  'had_onboard_call_with_staff',
                  'pref_role_1',
                  'pref_program',
                  'avail_am_class_online',
                  'avail_am_class_person',
                  'avail_pm_class_online',
                  'avail_pm_class_person',
                  'avail_citizen_class_online',
                  'class_level_prefs',
                  'pref_solo_indicator',
                  'co_teach_info',
                  'teacher_format_prefs',
                  'other_class_sched_info',
                  'tutor_type_pref',
                  'pref_tutor_slot',
                  'avail_am_tutor',
                  'avail_pm_tutor',
                  'avail_wknd_tutor',
                  'tutor_level_prefs',
                  'num_new_students',
                  'avail_before_sep_27_indicator',
                  'other_tutor_sched_info',
                  'pref_role_2',
                  'pref_program_2',
                  'avail_am_class_online_2',
                  'avail_am_class_person_2',
                  'avail_pm_class_online_2',
                  'avail_pm_class_person_2',
                  'avail_citizen_class_online_2',
                  'class_level_prefs_2',
                  'pref_solo_indicator_2',
                  'co_teach_info_2',
                  'teacher_format_prefs_2',
                  'open_to_accept_both_roles_indicator',
                  'other_class_sched_info_2',
                  'tutor_type_pref_2',
                  'pref_tutor_slot_2',
                  'avail_am_tutor_2',
                  'avail_pm_tutor_2',
                  'tutor_level_prefs_2',
                  'num_new_students_2',
                  'open_to_accept_both_roles_indicator_2',
                  'avail_before_sep_27_indicator_2',
                  'other_tutor_sched_info_2',
                  'interest_in_sub_list',
                  'address_1',
                  'address_2',
                  'city_state_zip',
                  'emerg_cont_first_name',
                  'emerg_cont_last_name',
                  'emerg_cont_phone',
                  'emerg_cont_relation',
                  'gender',
                  'birthday',
                  'race',
                  'ethnicity',
                  'native_langs',
                  'other_langs',
                  'highest_education',
                  'prior_experience',
                  'teach_certs',
                  'educ_credentials',
                  'employer',
                  'position',
                  'work_field',
                  'retired_past_work_field',
                  'med_conditions',
                  'med_details',
                  'trash_1',
                  'trash_2',
                  'trash_3',
                  'trash_4')


df <- df %>% select(-c('trash_1','trash_2','trash_3','trash_4'))


df_criteria <- df %>% select('first_name', 'last_name', 'email_address',
                             'gender','native_langs', 'other_langs',
                             'prior_experience', 'teach_certs', 'educ_credentials',
                             
                             'timestamp', 'proof_of_vax', 
                             'returning_indicator',
                             'previous_role',
                             'reserved_student_names',
                             'reregister_ackn_1',
                             'reregister_ackn_2',
                             'desired_start_date',
                             'details_multiple_dates',
                             'want_new_student_role_indicator',
                             'past_apply_not_placed',
                             'had_onboard_call_with_staff',
                             'pref_role_1',
                             'pref_program',
                             'avail_am_class_online',
                             'avail_am_class_person',
                             'avail_pm_class_online',
                             'avail_pm_class_person',
                             'avail_citizen_class_online',
                             'class_level_prefs',
                             'pref_solo_indicator',
                             'co_teach_info',
                             'teacher_format_prefs',
                             'other_class_sched_info',
                             'tutor_type_pref',
                             'pref_tutor_slot',
                             'avail_am_tutor',
                             'avail_pm_tutor',
                             'avail_wknd_tutor',
                             'tutor_level_prefs',
                             'num_new_students',
                             'avail_before_sep_27_indicator',
                             'other_tutor_sched_info',
                             'pref_role_2',
                             'pref_program_2',
                             'avail_am_class_online_2',
                             'avail_am_class_person_2',
                             'avail_pm_class_online_2',
                             'avail_pm_class_person_2',
                             'avail_citizen_class_online_2',
                             'class_level_prefs_2',
                             'pref_solo_indicator_2',
                             'co_teach_info_2',
                             'teacher_format_prefs_2',
                             'open_to_accept_both_roles_indicator',
                             'other_class_sched_info_2',
                             'tutor_type_pref_2',
                             'pref_tutor_slot_2',
                             'avail_am_tutor_2',
                             'avail_pm_tutor_2',
                             'tutor_level_prefs_2',
                             'num_new_students_2',
                             'open_to_accept_both_roles_indicator_2',
                             'avail_before_sep_27_indicator_2',
                             'other_tutor_sched_info_2'
)

df_criteria <- df_criteria %>% mutate(role = "Volunteer", status = "Unmatched")
write.csv(df_criteria, "../../data/volunteers.csv", row.names = FALSE) 

#For cases where 2nd and 3rd choice roles are not filled, drop

